name: flutter_lifetime_position
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  background_task: ^0.2.0+2
  permission_handler: ^11.3.1
  http: ^1.2.2
  shared_preferences: ^2.3.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.1
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.0
  riverpod_generator: ^2.4.0
  freezed: ^2.5.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  image: "assets/images/ic_launcher.png"
  color: "00808d"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher.png"
  adaptive_icon_background: "#00808d"
  adaptive_icon_foreground: "assets/images/ic_launcher.png"
